version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
      - yarn install --frozen-lockfile
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && yarn run pack"
artifacts:
  files:
    - "**/*"
  base-directory: dist
